### ISSUE TITLE
Layer is not displayed

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#8] opened 2017-06-02 09:50 UTC
### Current Behavior

Layer Colombie-corruption is not displayed 
### Steps to Reproduce

1.
2.
3.
...

**Comment by fxi** [comment] 2017-06-02 15:32
Is this happening on every zoom levels ?

**Comment by alejandraarango** [comment] 2017-06-02 16:01
Depend on the scale. 
Layer corruption and child labour in Congo and Colombia presented the same issue.

**Comment by fxi** [comment] 2017-06-06 11:45
I've removed the views presenting one value per country, as they will be part of a new global view category. The views used a scale with only one value : there is no visual variability across the polygon that represents the country, which does not make much sens in a cartographical representation of a country, at a country scale. 

Then, I was not able to reproduce this issue. Maybe something related to our server failure.

Fell free to reopen it if needed.

**Closed by fxi** 2017-06-06 11:45 UTC
