### ISSUE TITLE
Test PixOp tool - First results

### ISSUE THREAD

**Issue by antobenve** [fxi/map-x-mgl#335] opened 2018-10-08 15:09 UTC
## Majors
- [ ] Spotlights are generated in areas where there shouldn't be when increasing zoom (fig. 1)
- [ ] Spotlights are not generated where there should be (using lines). Problem increases when zoom is higher (fig. 2)

## Medium
- [ ] Overlap is not updated until the map is moved (sometimes) when a filter on map based on the secondary attributes is removed.
- [ ] Sometimes, during the same process (while the overlap is being computed), the selection/unselection of a secondary attribute doesn't update the input values of the overlap, which will not react until another input is given (eg. zoom of map is changed).
- [ ] When dragging the map during a simple overlap, the process is not fluid. Map is not moving until the left click is released and then can be moved without any click until the left button of the mouse is clicked again (not always of course but quite frequently is not fluid)

![image](https://user-images.githubusercontent.com/30286565/46616193-4ad71d00-cb1a-11e8-9e0f-00bee047748c.png)

![image](https://user-images.githubusercontent.com/30286565/46616170-3eeb5b00-cb1a-11e8-89a6-309182fb4bf8.png)

**Comment by fxi** [comment] 2018-10-09 05:51
Ok. 

I think those could be separated in individual issues : you put the label "bug", but you described improvement, performance and data-related bug. It could be confusing.

### Discontinuity

So, what you described looks like specific cases and not a general behaviour, as my tests using Points, LineString, Polygons and MultiPoints, MultiLineString and MultiPolygons did not reveal any of those.

However, I was able to reproduce discontinuity with the road network. So, I'm now looking for a pattern.

Here, the issue seems to be related with an inconsistency with the retrieved geometry: after a quick look under `mx.pixop.features`, I've extracted some fragments where mixed geometry types were used.

Example, road network with LineString (red) and MultilineString (black):

![image](https://user-images.githubusercontent.com/1196833/46648516-bd391300-cb95-11e8-9bfa-0e127001ffb5.png)

Produce this in PixOp:

![image](https://user-images.githubusercontent.com/1196833/46648566-f07ba200-cb95-11e8-8ea7-fd9abb328cb1.png)

Could you just try to create a short list of views pairs, with approximate location were this the discontinuity occurs ?
Example:

1. Project xy, Road Network - Population access to drinking water, [35.97, 68.48]

### Badly closed path

I can't find a pair of views with that issue, could you please also create a short list and approximate location ?

### General ideas

- Is this occuring with view uploaded recently ?
- Is this related to how the view was uploaded ? Form VS API VS previous iteration of the drag-and-drop

### Performance:

Generated tiles could be slow due to your local stack, that's true. But PixOp is completely running inside your browser. By the way, PixOp is launched in debug mode and you can retrieve all the performance timing in your console.

**Comment by antobenve** [comment] 2018-10-09 14:51
I couldn't experience any more the problem in Fig. 1 (the spotlights being generated where they shouldn't).

**Comment by fxi** [comment] 2018-10-10 05:51
I close this issue. The follow up is here #340

**Closed by fxi** 2018-10-10 05:51 UTC
Labels: Priority 1, bug
