### ISSUE TITLE
Error to Display layer Conflict Events in Afghanistan

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#12] opened 2017-06-14 13:31 UTC
### Current Behavior

The information of the Conflict events layer is not displayed properly. For display information is necessary to zoom in or out but in certain scale, half of the information is not displayed as is shown the image.
<img width="1239" alt="capture d ecran 2017-06-14 14 54 38" src="https://user-images.githubusercontent.com/28750477/27134204-2aac078c-5115-11e7-83ff-e543853f87dd.png">

### Steps to Reproduce

1. Display layer Conflict events in Afghanistan
2. Zoom out and zoom in 
3.
...

### Detailed Description

This is the only point type layer in Afghanistan. 
In Congo and Colombia the same layer exists but it works properly. Therefore this two layers are less heavy:
3.8 Mo Congo
5.7 Mo Colombia
27.1 Mo Afghanistan

**Comment by fxi** [comment] 2017-06-14 13:38
This was a cache issue, server side.
I've removed old cache, therefore, this should be ok.
If you edit and save the view, it will fetch another version of the tile.
Can you try it ?

**Comment by fxi** [comment] 2017-06-14 13:53
Great. 
I close this one. 
If this happen again, I will investigate the cause of the cache issue.
Thanks for reporting.

**Closed by fxi** 2017-06-14 13:53 UTC
