### ISSUE TITLE
 Feature request metadata form: Drop-down list in  access > role field

### ISSUE THREAD

**Issue by alejandraarango** [fxi/map-x-mgl#46] opened 2017-07-27 15:49 UTC
### Current Behavior

For those who do not have much experience with metadata, a guide of possible roles with the explanation can be very useful

### Possible Solution

 
Drop down list with categories of roles. I take the list/image from the Geonetwork.

See image: 
<img width="774" alt="capture d ecran 2017-07-27 16 49 26" src="https://user-images.githubusercontent.com/28750477/28679542-c72b72b4-72f3-11e7-97f3-797d4cad16ff.png">

**Comment by fxi** [comment] 2017-07-28 06:57
This is the expected behaviour and there was a bug when retrieving the publish target of the current editor. Therefore the fallback was a simple text field.

That's solved and will be available in the next update.

![image](https://user-images.githubusercontent.com/1196833/28705933-45a5f104-7372-11e7-88bc-808600415192.png)

**Comment by fxi** [comment] 2017-07-28 11:44
Possible duplicate of #15. Removed it.

**Closed** 2017-08-30 07:34 UTC
Labels: feature request, Fixed
